.cpu "65816"
.include "Floppy_def.asm"


* = $1C0000
INIFDD          JML IINITFFD
IFFDRESET       JML IFFDRESET
FDDREAD         JML IFDDREAD
FDDWRITE        JML IFDDWRITE
FDDSETSECTOR    JML IFDDSETSECTOR
FDDDSETTRACK    JML IFDDDSETTRACK
FDDSETSIDE      JML IFDDSETSIDE
FDDRECALIGRATE  JML IFDDRECALIGRATE
FDDSEEK         JML IFDDSEEK
FDDSEEKRELATIF  JML IFDDSEEKRELATIF


IINITFFD        BRK
IFFDRESET       BRK
IFDDREAD        BRK
IFDDWRITE       BRK
IFDDSETSECTOR   BRK
IFDDDSETTRACK   BRK
IFDDSETSIDE     BRK
IFDDRECALIGRATE BRK
IFDDSEEK        BRK
IFDDSEEKRELATIF BRK
